### ISSUE TITLE
When the API is super down, the API client behaves poorly

### ISSUE THREAD

**Issue by grahamc** [packethost/packet-python#45]
I got:

```
Traceback (most recent call last):
  File "./import.py", line 121, in <module>
    for device in get_devices(manager):
  File "./import.py", line 88, in get_devices
    data = manager.call_api(page)
  File "/nix/store/fn8qkd9vnr2p65707r6lwvpk9l3z29h5-python3-3.7.3-env/lib/python3.7/site-packages/packet/Manager.py", line 19, in call_api
    return super(Manager, self).call_api(method, type, params)
  File "/nix/store/fn8qkd9vnr2p65707r6lwvpk9l3z29h5-python3-3.7.3-env/lib/python3.7/site-packages/packet/baseapi.py", line 79, in call_api
    elif 'errors' in data:
TypeError: a bytes-like object is required, not 'str'
```

Turns out the API is replying with (in Python notation) `b'Forbidden\n'`.

**Comment by amenowanna** [comment]
@grahamc I apologize that this happened but this was expected due to an issue we had this morning. That has been resolved and we are currently monitoring.

**Comment by vielmetti** [comment]
The same error experienced in #79, for reference.

**Comment by grahamc** [comment]
Yeah, this issue was more like "there is a bug in the code" and not "the API was down, and this bug is reporting the API is down".

**Comment by vielmetti** [comment]
Reopening since this has more details than #79; closing that issue.

**Comment by grahamc** [comment]
Just for whatever it is worth, this issue is still happening :).

**Comment by displague** [comment]
A non-json error will return a string, this will attempt to be treated like an object in ResponseError:
https://github.com/packethost/packet-python/blob/3df8cdb/packet/baseapi.py#L105-L116

**Comment by grahamc** [comment]
Thanks, Marques!

**Comment by displague** [comment]
One example of this error is:

```
File "/.../.venv/lib64/python3.6/site-packages/packet/Manager.py", line 190, in create_device
"projects/%s/devices" % project_id, type="POST", params=params
File "/.../.venv/lib64/python3.6/site-packages/packet/Manager.py", line 32, in call_api
return super(Manager, self).call_api(method, type, params)
File "/.../.venv/lib64/python3.6/site-packages/packet/baseapi.py", line 116, in call_api
raise ResponseError(resp, data)
File "/.../.venv/lib64/python3.6/site-packages/packet/baseapi.py", line 28, in __init__
elif "error" in data:
TypeError: a bytes-like object is required, not 'str'
```

```
Sorry, you have been blocked
You are unable to access packet.net
```
